In [1]:
import joblib
import os
import numpy as np

#folder with saved estimations produced by PTF_GlueVaR_IS_sim.ipynb
filepath = ".../Resultate_final/PTF/IS/PTF_GlueVaR_IS_sim_saved/"

In [2]:
results_NN = []
results_RF = []

for filename in os.listdir(filepath):
    if filename != '.ipynb_checkpoints':
        results_NN.append(joblib.load(filepath+filename)[0])
        results_RF.append(joblib.load(filepath+filename)[1])
    
results_NN_avg = np.mean(results_NN,axis=0)
results_RF_avg = np.mean(results_RF,axis=0)
results_NN_var = np.var(results_NN,axis=0)
results_RF_var = np.var(results_RF,axis=0)

Averages and variances of resulting estimations and metrics. To see which value corresponds to what quantity, see how results are output at the end of PTF_sim.ipynb.

In [3]:
results_NN_avg

array([1.34960507e+03, 1.35046795e+03, 3.33242114e-02, 4.01967110e+00,
       2.87275796e-02, 1.71072092e-02, 1.07889519e+02])

In [4]:
results_RF_avg

array([ 1.15629231e+03,  1.33103811e+03,  2.70367104e-02, -1.38722588e+00,
       -7.74555933e-02,  1.04984356e-01,  1.07353722e+02])

In [5]:
results_NN_var

array([6.90400653e+02, 6.76000181e+02, 1.34086243e-01, 1.48271604e+03,
       1.28352904e-02, 3.31111896e-03, 1.34955043e-01])

In [6]:
results_RF_var

array([7.14717685e+02, 6.63626856e+01, 3.61797480e-03, 3.84162765e+01,
       6.80737596e-04, 3.63827309e-04, 4.41779144e-03])

In [7]:
len(os.listdir(filepath))

100