In [1]:
import joblib
import os
import numpy as np

#folder with saved estimations produced by PTF_GlueVaR_IS_sim.ipynb
filepath = ".../Resultate_final/PTF/IS/PTF_VaR_ES_IS_sim_saved/"

In [2]:
results_NN = []
results_RF = []

for filename in os.listdir(filepath):
    if filename != '.ipynb_checkpoints':
        results_NN.append(joblib.load(filepath+filename)[0])
        results_RF.append(joblib.load(filepath+filename)[1])
    
results_NN_avg = np.mean(results_NN,axis=0)
results_RF_avg = np.mean(results_RF,axis=0)
results_NN_var = np.var(results_NN,axis=0)
results_RF_var = np.var(results_RF,axis=0)

Averages and variances of resulting estimations and metrics. To see which value corresponds to what quantity, see how results are output at the end of PTF_sim.ipynb.

In [3]:
results_NN_avg

array([ 1.44370470e+03,  1.44538751e+03, -3.43991104e-02, -3.16969880e+00,
        6.89842224e-03,  3.08527861e-03,  1.10269000e+02,  1.10972830e+02])

In [4]:
results_RF_avg

array([ 1.24693517e+03,  1.43466864e+03,  3.11689806e-02, -9.85658702e-01,
       -4.97397269e-02,  9.02497364e-02,  1.09691524e+02,  1.10387364e+02])

In [5]:
results_NN_var

array([2.60687738e+03, 2.58591899e+03, 1.74688738e-01, 2.12452867e+03,
       7.89295552e-03, 2.13526019e-03, 1.89763367e-01, 1.94377180e-01])

In [6]:
results_RF_var

array([1.80512731e+03, 9.68156521e+02, 4.88373532e-03, 5.53331610e+01,
       7.55214954e-04, 4.03024111e-04, 1.16389041e-02, 1.14660929e-02])

In [7]:
len(os.listdir(filepath))

101