In [1]:
import joblib
import os
import numpy as np

#folder with saved estimations produced by Put_VaR_ES_IS_500_sim.ipynb
filepath = ".../Resultate_final/Put/IS/500/Put_VaR_ES_IS_500_sim_saved/"

In [2]:
results_NN = []
results_RF = []

for filename in os.listdir(filepath):
    if filename!='.ipynb_checkpoints':
        results_NN.append(joblib.load(filepath+filename)[0])
        results_RF.append(joblib.load(filepath+filename)[1])
    
results_NN_avg = np.mean(results_NN,axis=0)
results_RF_avg = np.mean(results_RF,axis=0)
results_NN_var = np.var(results_NN,axis=0)
results_RF_var = np.var(results_RF,axis=0)

Averages and variances of resulting estimations and metrics. To see which value corresponds to what quantity, see how results are output at the end of Put_sim.ipynb.

In [3]:
results_NN_avg

array([ 6.17241358e+01,  6.17129883e+01, -9.19624446e-04, -7.97114742e-03,
       -1.03008435e-03,  1.10459905e-04, -2.74936574e+00,  3.86850836e-01,
        8.26568230e+00,  8.42764095e+00])

In [4]:
results_RF_avg

array([ 6.07150072e+01,  6.07342254e+01, -6.58317024e-04,  5.57613213e-03,
       -6.64208491e-04,  0.00000000e+00, -2.62682264e+00,  4.48940366e-01,
        8.34371304e+00,  8.51294860e+00])

In [5]:
results_NN_var

array([2.58290839e+01, 2.58688983e+01, 9.73780295e-04, 7.66663020e-02,
       9.72344791e-04, 1.20793768e-06, 3.49302077e-01, 2.60360791e-03,
       3.06404651e-01, 3.32607439e-01])

In [6]:
results_RF_var

array([7.96202972e-01, 8.05556125e-01, 1.52861546e-04, 1.08474796e-02,
       1.52833082e-04, 0.00000000e+00, 1.09162914e-02, 1.30345165e-03,
       3.91639423e-04, 8.23012774e-05])

In [7]:
len(os.listdir(filepath))

100