In [1]:
import joblib
import os
import numpy as np

#folder with saved estimations produced by Put_GlueVaR_IS_500_sim.ipynb
filepath = ".../Resultate_final/Put/IS/500/Put_GlueVaR_IS_500_sim_saved/"

In [2]:
results_NN = []
results_RF = []

for filename in os.listdir(filepath):
    if filename!='.ipynb_checkpoints':
        results_NN.append(joblib.load(filepath+filename)[0])
        results_RF.append(joblib.load(filepath+filename)[1])
    
results_NN_avg = np.mean(results_NN,axis=0)
results_RF_avg = np.mean(results_RF,axis=0)
results_NN_var = np.var(results_NN,axis=0)
results_RF_var = np.var(results_RF,axis=0)

Averages and variances of resulting estimations and metrics. To see which value corresponds to what quantity, see how results are output at the end of Put_sim.ipynb.

In [3]:
results_NN_avg

array([ 5.73181095e+01,  5.73153234e+01,  5.78356867e-04,  5.13919189e-03,
        6.46792877e-04, -7.38245879e-05, -2.22658343e+00,  4.63827110e-01,
        7.64840741e+00])

In [4]:
results_RF_avg

array([ 5.57148677e+01,  5.57427867e+01,  1.09696045e-03,  1.75750046e-02,
        8.90092314e-04,  2.22028173e-06, -2.05165342e+00,  5.21013880e-01,
        7.69213471e+00])

In [5]:
results_NN_var

array([1.62292571e+01, 1.61926330e+01, 8.62123038e-04, 5.58344812e-02,
       8.61285845e-04, 5.39556909e-07, 2.04917168e-01, 9.84425560e-04,
       1.76280416e-01])

In [6]:
results_RF_var

array([2.41968428e-01, 2.49164202e-01, 1.47298177e-04, 8.54782183e-03,
       1.47991990e-04, 4.28929689e-11, 2.82766072e-03, 3.79506043e-04,
       1.34676418e-04])

In [7]:
len(os.listdir(filepath))

100