In [1]:
import joblib
import os
import numpy as np

#folder with saved estimations produced by Put_sim.ipynb
filepath = ".../Resultate_final/Put/saved_sim/"

In [2]:
#load results
results_NN = []
results_RF = []

for filename in os.listdir(filepath):
    if filename != '.ipynb_checkpoints':
        results_NN.append(joblib.load(filepath+filename)[0])
        results_RF.append(joblib.load(filepath+filename)[1])
    
results_NN_avg = np.mean(results_NN,axis=0)
results_RF_avg = np.mean(results_RF,axis=0)
results_NN_var = np.var(results_NN,axis=0)
results_RF_var = np.var(results_RF,axis=0)

Averages and variances of resulting estimations and metrics. To see which value corresponds to what quantity, see how results are output at the end of Put_sim.ipynb.

In [3]:
results_NN_avg

array([3.63571745e+01, 3.63559987e+01, 2.06636956e-03, 8.34110696e-03,
       2.46274449e-03, 1.85747734e-03, 8.31561273e+00, 8.45047675e+00,
       7.66730719e+00])

In [4]:
results_RF_avg

array([ 3.63204714e+01,  3.63691445e+01,  3.30013443e-04,  2.18656641e-02,
        6.37615704e-04, -1.14295354e-04,  8.34797244e+00,  8.52923129e+00,
        7.71345949e+00])

In [5]:
results_NN_var

array([3.33842053e-03, 9.24145549e-03, 6.05246880e-04, 1.56494546e-02,
       2.97474451e-04, 5.73874194e-05, 1.30520799e-02, 1.69391605e-02,
       7.07836247e-03])

In [6]:
results_RF_var

array([3.30784225e-03, 9.62654503e-03, 1.11083274e-04, 2.48514626e-03,
       4.68744593e-05, 2.09010210e-05, 1.45952663e-02, 3.46398195e-03,
       1.35005625e-03])

In [7]:
len(os.listdir(filepath))

100