In [1]:
import joblib
import os
import numpy as np

#folder with saved estimations produced by Put_GlueVaR_IS_250_sim.ipynb
filepath = ".../Resultate_final/Put/IS/250/Put_GlueVaR_IS_250_sim_saved/"

In [2]:
results_NN = []
results_RF = []

for filename in os.listdir(filepath):
    if filename!='.ipynb_checkpoints':
        results_NN.append(joblib.load(filepath+filename)[0])
        results_RF.append(joblib.load(filepath+filename)[1])
    
results_NN_avg = np.mean(results_NN,axis=0)
results_RF_avg = np.mean(results_RF,axis=0)
results_NN_var = np.var(results_NN,axis=0)
results_RF_var = np.var(results_RF,axis=0)

Averages and variances of resulting estimations and metrics. To see which value corresponds to what quantity, see how results are output at the end of Put_sim.ipynb.

In [3]:
results_NN_avg

array([ 5.62925817e+01,  5.62944964e+01, -3.58741430e-03, -2.66113997e-02,
       -3.77459364e-03,  1.78293678e-04, -2.11060976e+00,  4.48945831e-01,
        7.54580507e+00])

In [4]:
results_RF_avg

array([ 5.58642303e+01,  5.59073935e+01, -1.10359372e-03,  2.60515890e-03,
       -1.28644770e-03,  1.39044537e-06, -2.06692074e+00,  5.12435892e-01,
        7.69218759e+00])

In [5]:
results_NN_var

array([4.89870112e+01, 4.88279963e+01, 7.55787412e-04, 4.84439624e-02,
       7.50773323e-04, 3.61117844e-06, 6.15549425e-01, 3.76952038e-03,
       4.73586129e-01])

In [6]:
results_RF_var

array([2.99804115e-01, 3.04010997e-01, 1.17511529e-04, 6.69073161e-03,
       1.17850783e-04, 5.25594448e-11, 3.45362223e-03, 4.73453835e-04,
       1.12691894e-04])

In [7]:
len(os.listdir(filepath))

100