In [1]:
import joblib
import os
import numpy as np

#folder with saved estimations produced by Put_VaR_ES_IS_250_sim.ipynb
filepath = ".../Resultate_final/Put/IS/250/Put_VaR_ES_IS_250_sim_saved/"

In [2]:
results_NN = []
results_RF = []

for filename in os.listdir(filepath):
    if filename!='.ipynb_checkpoints':
        results_NN.append(joblib.load(filepath+filename)[0])
        results_RF.append(joblib.load(filepath+filename)[1])
    
results_NN_avg = np.mean(results_NN,axis=0)
results_RF_avg = np.mean(results_RF,axis=0)
results_NN_var = np.var(results_NN,axis=0)
results_RF_var = np.var(results_RF,axis=0)

Averages and variances of resulting estimations and metrics. To see which value corresponds to what quantity, see how results are output at the end of Put_sim.ipynb.

In [3]:
results_NN_avg

array([ 6.02884669e+01,  6.02846319e+01,  5.26229842e-03,  4.98811126e-02,
        5.10669715e-03,  1.55601269e-04, -2.58120085e+00,  3.61649066e-01,
        8.12560016e+00,  8.27777952e+00])

In [4]:
results_RF_avg

array([ 6.08317245e+01,  6.08558974e+01,  5.92195730e-04,  1.92991063e-02,
        5.90896469e-04,  0.00000000e+00, -2.64004656e+00,  4.34130532e-01,
        8.34149941e+00,  8.51353880e+00])

In [5]:
results_NN_var

array([7.34828620e+01, 7.34979147e+01, 9.31375810e-04, 7.04858306e-02,
       9.29911989e-04, 3.05303739e-06, 9.91796525e-01, 5.20113058e-03,
       9.56683493e-01, 1.03582529e+00])

In [6]:
results_RF_var

array([7.46170358e-01, 7.66645372e-01, 1.46354125e-04, 1.08916597e-02,
       1.46338700e-04, 0.00000000e+00, 1.05205712e-02, 1.05709031e-03,
       3.91157892e-04, 9.12063796e-05])

In [7]:
len(os.listdir(filepath))

101