In [1]:
import joblib
import os
import numpy as np

#folder with saved estimations produced by Put_VaR_ES_IS_750_sim.ipynb
filepath = ".../Resultate_final/Put/IS/750/Put_VaR_ES_IS_750_sim_saved/"

In [2]:
results_NN = []
results_RF = []

for filename in os.listdir(filepath):
    if filename!='.ipynb_checkpoints':
        results_NN.append(joblib.load(filepath+filename)[0])
        results_RF.append(joblib.load(filepath+filename)[1])
    
results_NN_avg = np.mean(results_NN,axis=0)
results_RF_avg = np.mean(results_RF,axis=0)
results_NN_var = np.var(results_NN,axis=0)
results_RF_var = np.var(results_RF,axis=0)

Averages and variances of resulting estimations and metrics. To see which value corresponds to what quantity, see how results are output at the end of Put_sim.ipynb.

In [3]:
results_NN_avg

array([ 6.24688640e+01,  6.24711516e+01,  2.41322296e-03,  2.74038352e-02,
        2.41322296e-03,  0.00000000e+00, -2.83617497e+00,  4.02389230e-01,
        8.34150924e+00,  8.50983000e+00])

In [4]:
results_RF_avg

array([ 6.13523586e+01,  6.13920142e+01,  1.02193361e-04,  1.39622281e-02,
        1.01992796e-04,  0.00000000e+00, -2.70287376e+00,  4.32694705e-01,
        8.33999432e+00,  8.51286875e+00])

In [5]:
results_NN_var

array([7.88192719e-03, 1.36189858e-02, 9.32468858e-04, 7.54930649e-02,
       9.32468858e-04, 0.00000000e+00, 3.03798864e-05, 5.07858175e-04,
       4.38183320e-03, 3.41503966e-03])

In [6]:
results_RF_var

array([4.37909753e-01, 4.47184062e-01, 1.77873708e-04, 1.33513776e-02,
       1.77880733e-04, 0.00000000e+00, 6.13247559e-03, 6.22284633e-04,
       3.73548771e-04, 6.60590122e-05])

In [7]:
len(os.listdir(filepath))

100