In [1]:
import joblib
import os
import numpy as np

#folder with saved estimations produced by VarAnn_sim.ipynb
filepath = ".../Resultate_final/VarAnn/saved_sim/"

In [2]:
#load results
results_NN = []
results_RF = []

for filename in os.listdir(filepath):
    if filename != '.ipynb_checkpoints':
        results_NN.append(joblib.load(filepath+filename)[0])
        results_RF.append(joblib.load(filepath+filename)[1])
    
results_NN_avg = np.mean(results_NN,axis=0)
results_RF_avg = np.mean(results_RF,axis=0)
results_NN_var = np.var(results_NN,axis=0)
results_RF_var = np.var(results_RF,axis=0)

Averages and variances of resulting estimations and metrics. To see which value corresponds to what quantity, see how results are output at the end of PTF_sim.ipynb.

In [3]:
results_NN_avg

array([3.73747821e+03, 3.08290830e+03, 4.24514417e-03, 7.47986590e-01,
       1.23106510e-02, 1.54309702e-02, 1.38914433e+02, 1.40314411e+02,
       1.32837722e+02])

In [4]:
results_RF_avg

array([ 3.72883220e+03,  3.07091739e+03, -4.64589159e-03, -7.77914199e-02,
       -8.12523290e-03,  7.64155879e-03,  1.40390664e+02,  1.41153172e+02,
        1.33064838e+02])

In [5]:
results_NN_var

array([1.20296041e+07, 3.67559194e+06, 2.71744940e-01, 3.02715245e+03,
       4.93281540e-02, 1.53738553e-02, 2.34851018e+00, 2.73470872e+00,
       1.58630040e+00])

In [6]:
results_RF_var

array([1.20082627e+07, 3.44460211e+06, 6.83603421e-03, 8.88671415e+01,
       3.22483223e-03, 1.25891893e-03, 7.44510167e-01, 1.08168974e+00,
       4.01832553e-01])

In [7]:
len(os.listdir(filepath))

101