In [1]:
import joblib
import os
import numpy as np

#folder with saved estimations produced by PTF_sim.ipynb
filepath = ".../Resultate_final/PTF/saved_sim/"

In [2]:
#load results
results_NN = []
results_RF = []

for filename in os.listdir(filepath):
    results_NN.append(joblib.load(filepath+filename)[0])
    results_RF.append(joblib.load(filepath+filename)[1])
    
results_NN_avg = np.mean(results_NN,axis=0)
results_RF_avg = np.mean(results_RF,axis=0)
results_NN_var = np.var(results_NN,axis=0)
results_RF_var = np.var(results_RF,axis=0)

Averages and variances of resulting estimations and metrics. To see which value corresponds to what quantity, see how results are output at the end of PTF_sim.ipynb.

In [3]:
results_NN_avg

array([ 1.15679403e+03,  1.15736459e+03, -6.71936154e-02, -5.73550722e+00,
       -6.69023114e-04, -6.56350587e-03,  1.10034073e+02,  1.10644089e+02,
        1.07608682e+02])

In [4]:
results_RF_avg

array([ 1.03477886e+03,  1.16036785e+03,  1.50480280e-02, -2.92103903e+00,
       -1.24045513e-01,  1.17560803e-01,  1.06932166e+02,  1.07534317e+02,
        1.04975096e+02])

In [5]:
results_NN_var

array([2.79269674e+00, 9.56644053e+00, 1.49703536e-01, 1.32927616e+03,
       1.05934057e-02, 1.08023162e-02, 4.72669665e-01, 5.14331695e-01,
       3.67878823e-01])

In [6]:
results_RF_var

array([2.17175532e+00, 8.82392913e+00, 3.16851891e-03, 2.90162300e+01,
       5.78300969e-04, 6.63142341e-04, 2.73872635e-02, 3.78033366e-02,
       1.61888007e-02])

In [7]:
len(os.listdir(filepath))

101